source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

#Javascript runtime
#gem 'execjs'
#gem 'johnson'

#required for omniauth until they put the dependency in
gem 'bcrypt-ruby', '~> 3.0.0'

#Sessions
#https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
gem 'devise' #https://github.com/plataformatec/devise

#Gems for authorizing with other services, potentially many: 
# https://github.com/intridea/omniauth/wiki/List-of-Strategies
# each needs configuration
# gem 'omniauth' #https://github.com/intridea/omniauth
gem 'omniauth-facebook' #https://github.com/mkdynamic/omniauth-facebook
# gem 'omniauth-twitter' #https://github.com/arunagw/omniauth-twitter
# gem 'omniauth-openid' #https://github.com/intridea/omniauth-openid
# gem 'omniauth-identity' #https://github.com/intridea/omniauth-identity
# gem 'omniauth-github' #https://github.com/intridea/omniauth-github
# gem 'omniauth-linkedin' #https://github.com/skorks/omniauth-linkedin

gem 'rdiscount'